baatKar/baatKar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('chatapp.urls', namespace='chatapp')),
    url(r'^profile/', include('chatapp.urls', namespace='chatapp')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baatKar/chatapp/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
        profile,
        Home,
        Post,
        Messages
)

urlpatterns = [
    url(r'^$', profile, name='profile'),
    url(r'^home/(?P<receiver>[A-Za-z0-9]+)$', Home, name='home'),
    url(r'^post/$', Post, name='post'),
    url(r'^messages/(?P<receiver>[A-Za-z0-9]+)$',Messages, name='messages'),

]

baatKar/chatapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    message = models.CharField(max_length=200)
    receiver = models.ForeignKey(User, related_name = 'receiver_user')
    received_at = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.message

baatKar/chatapp/views.py
from django.shortcuts import render
from allauth.account.decorators import  login_required
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from .models import Chat
from django.db.models import Q

@login_required
def profile(request):
    users = User.objects.all()
    users = users.exclude(username=request.user)
    context = {
        "users": users,
    }
    return render(request, "profile.html", context)

@login_required
def Home(request, receiver):
    print("Home")
    print("sender: ", request.user)
    print("receiver: ", receiver)
    try:
        c = Chat.objects.filter( Q(user=request.user) |
                                 # Q(receiver=User.objects.get(username=receiver)) |
                                 Q(user= User.objects.get(username=receiver))
                                 # Q(receiver= request.user)
                                 )
        c = c.filter(
            Q(receiver=User.objects.get(username=receiver)) |
            Q(receiver=request.user)

        )
        c = c.extra(order_by=['created'])
        print("fine")
    except Exception as e:
        print("Except")
        print(e)
        c = Chat.objects.filter(user = request.user)
    return render(request, "home.html", {'home': 'active', 'chat': c, 'receiver': receiver})

@login_required
def Post(request):
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        receiver = request.POST.get('receiver', None)
        # msg = request.POST.get('msgbox', None)


        print(request.user.username)
        print(receiver)
        c = Chat(user=User.objects.get(username=request.user.username), message=msg, receiver=User.objects.get(username=receiver))
        if msg != '':
            c.save()
        return JsonResponse({ 'msg': msg, 'user': c.user.username })
    else:
        return HttpResponse('Request must be POST.')

@login_required
def Messages(request, receiver):
    print("Messages")
    print("sender: ", request.user.username)
    print("receiver: ", receiver)
    # c = Chat.objects.filter(user=request.user)
    try:
        c = Chat.objects.filter( Q(user=request.user) |
                                 Q(user= User.objects.get(username=receiver))
                                 )
        c = c.filter(
            Q(receiver=User.objects.get(username=receiver)) |
            Q(receiver=request.user)

        )
        c = c.extra(order_by=['created'])
        print("fine")
    except Exception as e:
        print("Except")
        print(e)
        c = Chat.objects.filter( user = request.user)
    return render(request, 'messages.html', {'chat': c, 'receiver': receiver})

baatKar/templates/base.html
<!DOCTYPE html>
<html>
        <head>
            <title>{% block head_title %}{% endblock head_title %}</title>
        </head>
        <body>
            {% block body %}
            {% block content %}
            {% endblock content %}
            {% endblock body %}
            {% block extra_body %}
            {% endblock extra_body %}
        </body>
</html>

baatKar/templates/home.html
{% load staticfiles %}

<html>

<head>
    <title>Chat Panel</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'chat.css' %}">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

<body>
    <div id="chat-body" class="panel panel-default">
        <div class="panel-heading">Tratoli Chat</div>
        <div id="msg-list-div" class="panel-body">
            <ul id="msg-list" class="list-group">
                {% for obj in chat %}
                    {% if obj.user.username == request.user.username %}
                        <li class="text-right list-group-item">{{ obj.message }}</li>
                    {% else %}
                        <li class="text-left list-group-item">{{ obj.message }}</li>
                    {% endif %}
                {% empty %}
                    <li class="text-right list-group-item">No messages yet!</li>
                {% endfor %}
                <script>
                    var chatlist = document.getElementById('msg-list-div');
                    chatlist.scrollTop = chatlist.scrollHeight;
                </script>
            </ul>
        </div>
    </div>

    <form id="chat-form" method="post" action="/post/">
        <div id="chat-bottom" class="input-group">
            <input type="text" id="chat-msg" name="chat-msg" class="form-control"/>
            <input type="hidden" id="receiver-name" name="receiver-name" class="form-control" value={{receiver}} />
            <span class="input-group-btn">
                <input class="btn btn-default" id="send" type="submit" value="Send"/>
            </span>
        </div>
    </form>
</body>

<script src="{% static 'chat.js' %}"></script>
</html>

baatKar/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

baatKar/templates/messages.html
{% for obj in chat %}
    {% if obj.user == request.user %}
        <li class="text-right list-group-item">{{ obj.message }}</li>
    {% else %}
        <li class="text-left list-group-item">{{ obj.message }}</li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">No messages yet!</li>
{% endfor %}

baatKar/templates/profile.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'chat.css' %}">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

{% load account %}

<h2>Current User: <span class="label label-success">{% user_display user %}</span> <span class="label label-danger"><a href="{% url 'account_logout' %}" style="color: inherit; ">Logout</a></span></h2>

<div class="list-group">
<H2 class="list-group-item active">Avalible users to chat.</H2>
<ul class="list-group" >
{% for user in users %}
    <li class="list-group-item">
        <h3>{{user }} | {{user.email}} | <small> <a href= {% url 'chatapp:home' user %} target="_blank"> [chat] </a></small></h3>
        </li>
{% endfor %}
    </ul>
    </div>
</body>
</html>